services:
  - type: web
    name: sistema-recoleccion-facatativa
    runtime: python
    repo: https://github.com/juliancamilos86-art/Sistema-de-Recolecci-n-Facatativ-
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_REDIRECT_URI
        value: https://sistema-de-recolecci-n-facatativ.onrender.com/callback