services:
  - type: web
    name: sistema-recoleccion-facatativa
    runtime: python
    repo: https://github.com/juliancamilos86-art/Sistema-de-Recolecci-n-Facatativ-
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dcahg6ff3
      - key: CLOUDINARY_API_KEY
        value: 839728325267682
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AZURE_CLIENT_ID
        value: 6c90a6e0-afdb-401b-bf89-ffccccf80d31
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: AZURE_TENANT_ID
        value: 338f1914-5f2b-4c1e-94e1-b29347c7b31f
      - key: AZURE_REDIRECT_URI
        value: https://sistema-de-recolecci-n-facatativ-pnyf.onrender.com/auth/microsoft/callback
      - key: SECRET_KEY
        generateValue: true